# Read in data
Load in useul packages.
```{r packages, warning=FALSE}
library(sf)
library(tidyverse)
library(here)
library(janitor)
library(countrycode)
```

Read in csv and shapefile data.
```{r reading file, warning=FALSE}
HDI <- read_csv(here("homework4_data","HDR21-22_Composite_indices_complete_time_series.csv"),
                locale = locale(encoding = "latin1"),
                na = "",skip = 0)
World <- st_read(here("homework4_data","World_Countries_(Generalized)","World_Countries__Generalized_.shp"))
```
Selecting the gender inequality data for 2010 and 2019, calculating their difference. The countries in World are indexed using 2 digits ISO code. So we convert `country` or `iso` into it for the join later.
```{r selecting HDI columns}
HDIselected <- HDI %>% 
  clean_names() %>% 
  select(iso3, country, gii_2010, gii_2019) %>% 
  mutate(difference = gii_2019 - gii_2010) %>% 
  mutate(iso_code = countrycode(country, origin = 'country.name', destination = 'iso2c')) %>% 
  mutate(iso_code2 = countrycode(iso3, origin = 'iso3c', destination = 'iso2c'))
```

Join the csv file to the world shape file
```{r join}
join_HDI <- World %>% 
  clean_names() %>% 
  left_join(., HDIselected, 
            by = c("iso" = "iso_code"))
```

